name = "spanish-learning-app"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_dir = "dist"

[site]
bucket = "./dist"
entry-point = "dist/index.html"

[env.production]
vars = { NODE_ENV = "production" }

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
